spring:        
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://ggnlabvm-mqoe03:3306/identityManagement
        username: root
        password: hsc321
        driver-class-name: com.mysql.jdbc.Driver
