server:
    port:  8761

eureka:
    instance:
        hostname: ggnlabvm-mqoe03
    client:
        serviceUrl:
            defaultZone: http://ggnlabvm-mqoe02:8761/eureka/
#        register-with-eureka: false
#        fetch-registry: false
        
logging:
    level:
        com:
           netflix:
               eureka: OFF
               discovery: OFF
